DELETE https://gentle-ocean-20972.herokuapp.com/api/persons/951195
###

GET http://localhost:3001/api/persons

###

POST https://gentle-ocean-20972.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{ 
    "name": "Liisa Marttinen", 
    "number": "040-243563"
}

###

PUT http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{ 
    "name": "Liisa Marttinen", 
    "number": "040-24563"
}